### ISSUE TITLE
"Input data is not a valid GeoJSON object."

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [uber/react-map-gl#1033]
hi, I am using the GEO-JSON example. when I try to run it shows this error "Input data is not a valid GeoJSON object."

it is a similar example that is in this url ```https://github.com/uber/react-map-gl/tree/5.2-release/examples/geojson```

example in codesandbox : ```https://codesandbox.io/s/map-color-geojson-zzmmv```

please help me with that.

**Comment by bilafish** [comment]
Hi @DhanushkumarSivaji , have fixed it [here](https://codesandbox.io/s/map-color-geojson-jjzg4).

Seems that your variable type for data to the React component, <Source> was not set correctly when you called setData. Instead of a object with nested key 'data', it should just be the GeoJson object. Also, I changed the initated state for data to null as per the example in the repo.

**Comment by DhanushkumarSivaji** [comment]
THANKS MAN..YOU FIXED MY ISSUE .... :)
