### ISSUE TITLE
fitBounds returns a zoom level of NaN

### ISSUE THREAD

**Issue by esamelson** [uber/react-map-gl#111]
Hello,

I am running into an issue in that `fitBounds` is returning an object whose `zoom` property is NaN. However, the `latitude` and `longitude` properties seem to be working correctly, as they are at a location where I would expect the center of the viewport to be. I have looked into the source code a bit, but I am unfamiliar with the Transform library so I am unsure as to where the issue might be. I don't think the issue is with my direct input to `fitBounds`, as the `latitude` and `longitude` are correct, but I could be wrong. Any ideas?

Thanks very much.

**Comment by ibgreen** [comment]
@esamelson You could probably single step through the [fitBounds](https://github.com/uber/react-map-gl/blob/master/src/fit-bounds.js) code and see where the zoom calculations go wrong and the NaN appears, that would be helpful. If not, it would probably be easiest to debug this if we could write a test case for it.

Either you can open a PR with a new test case, or provide the failing input/outputs to the function so that we can write one.

If you want to go the PR route, please add a test case in test directory, something like:

```
import {fitBounds} from '../src';

test('fitBounds', t => {
  const result = fitBounds(<Your failing parameters go here>);
  t.equal(result.latitude, ..., 'got expected latitude');
  t.equal(result.longitude, ..., 'got expected latitude');
  t.equal(result.zoom, ..., 'got expected zoom');  
  t.end();
});
```

Note, you would need to sign our open source contributor form as well.

**Comment by esamelson** [comment]
Well, I stepped through the fitBounds code and discovered the error was on my end after all. So sorry for wasting your time @ibgreen .
