### ISSUE TITLE
cut release for v1.8.0 with mapbox-gl 0.31.0; hard dependency needed on Node V4

### ISSUE THREAD

**Issue by abmai** [uber/react-map-gl#182]
Wanted to start an async convo about this before possibly proceeding. There's a Node v4 hard dependency on moving to mapbox-gl >= 0.27.0. I think it's fine because this comes from upgrading mapbox-gl and we should set an expectation to track them as closely as possible.

@ibgreen @apercu thoughts?

**Comment by Apercu** [comment]
Strongly agree on this one, and would rather go for the last LTS (6.9.4) instead, while we're at it.

**Comment by ibgreen** [comment]
> cut release for v1.8.0 with mapbox-gl 0.31.0; hard dependency needed on Node V4

@abmai - Sounds good. I would personally recommend a major version bump, since at least one of our applications was confirmed to break with this change. Seems like a small price to pay for the extra peace of mind? We could bump master to 2.0 now and move dev to 3.0.0-beta.

PS- How would we make the hard dependency on Node >= 4.0? Would it be implicit/in documentation or would we use something like [`engineStrict`](http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html)?

> would rather go for the last LTS (6.9.4) instead

@apercu - I see the appeal, but won't we risk causing problems for some external users who might still be on Node 4 if we refuse to install react-map-gl on Node < 6? According to [Node LTS plan](https://github.com/nodejs/LTS) Node 4 will be maintained until April 2018. Maybe we should instead add Node 4 to our Travis test matrix?

**Comment by abmai** [comment]
There's no real need (yet) to force users to be on Node v6. The "hard" dependency on Node v4 here is from `mapbox-gl` >= 0.27.0 dependency on `unflowify` which uses `Object.assign` natively, which is only supported on Node >= v4.

Going to v2.0.0 with this first and make dev v3.0.0 is also not a bad idea. That would ensure no breakage to existing apps while people still have a path to get to the latest mapbox-gl version if they have the environment setup.

**Comment by Apercu** [comment]
I never said to force users to use Node 6, were we talking about the engines? `>= 4` looks good, but I don't think we should refrain from using lastest ones ourselves.

**Comment by abmai** [comment]
Sorry - I should've been clearer in my OP. I agree that for us (and the apps we work on internally) should go to v6+.

I'll bump this to v2.0.0 to make sure it doesn't cause any breakage at this point - unless there are objections.

**Comment by abmai** [comment]
Bumped to v2.0.0
