### ISSUE TITLE
Unable to disable the drag event

### ISSUE THREAD

**Issue by DinoJay** [uber/react-map-gl#195]
I'm currently working on a custom overlay. I want to enable zoom without the mousedrag behavior. It works by setting the following props:  
```
viewport.isDragging = false;
viewport.startDragLngLat = false;
```

Unfortunately, I got the following exception when a drag event is fired:
```
Uncaught AssertionError {name: "AssertionError", actual: null, expected: true, operator: "==", message: "`startDragLngLat` prop is required for mouse drag behavior to calculate where to position the map."…}actual: nullexpected: truegeneratedMessage: falsemessage: "`startDragLngLat` prop is required for mouse drag behavior to calculate where to position the map."name: "AssertionError"operator: "=="stack: "AssertionError: `startDragLngLat` prop is required for mouse drag behavior to calculate where to position the map.    at MapGL._onMouseDrag (https://127.0.0.1:8888/bundle.js:58561:28)    at Interactions._onMouseDrag (https://127.0.0.1:8888/bundle.js:57560:20)"__proto__: Error
fail @ assert.js:195
ok @ assert.js:215
_onMouseDrag @ map.react.js:795
_onMouseDrag @ map-interactions.react.js:202
```

Is there a nicer way to achieve that functionality?

Best,
Jan

**Comment by abmai** [comment]
hey @DinoJay - both `isDragging` and `startDragLngLat` are internal variables and shouldn't be modified directly. They're only exposed because of the stateless paradigm that the library was originally created under.

Are you trying to disable the entire drag event? Or you just don't want the map to be moved. If it's the latter, you can just ignore the `latitude/longitude` that gets passed back to `onChangeViewport` (and not pass it back into the react-map-gl instance).

**Comment by DinoJay** [comment]
Actually, I'm working with a SVG overlay. But when I trigger a `drag` event the map get shifted and the SVG elements are not updated until I release the mouse again. What I want to achieve is to keep the map interactive by passing back the `latitude` and `longitude` props. But I also want to disable the drag to keep the svg points always in sync with the underlying map layer.
