### ISSUE TITLE
isBrowser check breaks in Electron

### ISSUE THREAD

**Issue by jonmanzo** [uber/react-map-gl#243]
Running in Electron, the below isBrowser check evaluates to false
static-map
`if (isBrowser) {
  mapboxgl = require('mapbox-gl');
  ({Point} = mapboxgl);
}`

All good until here:
`mapboxgl.accessToken = props.mapboxApiAccessToken;`
As this will throw seeing as mapboxgl === null.

Workaround (using Webpack): set process.browser = true.

**Comment by ibgreen** [comment]
> Running in Electron, the below isBrowser check evaluates to false

Thanks for reporting. Sounds like we should add guards against the mapbox-gl require returning null, and be more gentle when destructuring the Point type.

**Comment by PilotConway** [comment]
This is a big issue for me right now. isBrowser results in false because `process.browser` in undefined in `electron. require('electron).remote.process.browser` is what holds the true value. 

For electron builds we need a way to bypass the isBrowser check and force the `require('mapbox-gl')` to load, or, the check needs to be better about knowing it can load mapbox-gl fine.

I've tried all sorts of setting process.browser = true in all kinds of places but none of them work.

**Comment by ibgreen** [comment]
In luma.gl (one of our other frameworks) we added an `is-electron` file to handle this case, see:

* https://github.com/uber/luma.gl/blob/master/src/utils/is-electron.js
* https://github.com/uber/luma.gl/blob/master/src/utils/is-browser.js

Maybe it could be starting point for a PR?

**Comment by PilotConway** [comment]
Yeah, that definitely seems to be something that works. Just tried a local copy with those two files and it loaded the map. 

There's still a difference using that versus using `process.browser = true` that's causing the mouse controls to not work correctly, looking into why that's happening now.

**Comment by PilotConway** [comment]
https://github.com/uber-web/mjolnir.js has the same browser check. Changing that as well allows the mouse gestures to work as expected. 

https://github.com/uber-web/mjolnir.js/blob/d76e73c878dfebaaf20bc4b634e74fe8762023da/src/utils/globals.js#L48
