### ISSUE TITLE
[RFC] Update mapbox-gl-js to latest version; plan for tracking mapbox versions

### ISSUE THREAD

**Issue by abmai** [uber/react-map-gl#257]
Two things I want to discuss with this issue:

**1.** We're using `0.32.1` and the latest version is `0.37.0`:

https://github.com/mapbox/mapbox-gl-js/releases

There's been a few breaking API changes on their end, copied here for convenience. They also have new features that you can check out in the actual release log.

#### :warning: Breaking changes

- Removed `LngLat#wrapToBestWorld`

#### :warning: Breaking changes
- Automatically add Mapbox wordmark when required by Mapbox TOS
- Increase default `maxZoom` from 20 to 22
- Deprecate `tiledata` and `tiledataloading` events in favor of `sourcedata` and `sourcedataloading`.
- `mapboxgl.util` is no longer exported
- `"type": "categorical"` is now required for all categorical functions. Previously, some forms of "implicitly" categorical functions worked, and others did not.

**2.** How do we want to establish a tracking cadence with mapbox-gl-js versions going forward?

Looking at their changelog, we should expect a new version from them every 2~3 weeks. Do we just revisit every month or so and pull ourselves to whatever latest version is at the time. Or do we make an effort to upgrade as soon as possible.

@ibgreen @Pessimistress @shaojingli @ericsoco

**Comment by ibgreen** [comment]
> How do we want to establish a tracking cadence with mapbox-gl-js versions going forward?

It would be nice to be able to stay in sync and keep publishing minor versions when mapbox upgrades. 
* Sometimes it is just a matter of bumping the `mapbox-gl` version in package.json, do a regression test round (the important part) and republish.
* Sometimes they have a new API - which might be the big deal with that release, so saying that we have bumped without supporting the new feature might be confusing. We would need to make a decision whether to expose it.
* Some of their changes are breaking, which would technically mean  `react-map-gl` should bump major version. Fortunately, many of their breaking changes are not be visible through our API (e.g. the `mapboxgl.util` removal above) so it may largely be a non-issue.

Some more extreme ideas:
* Align our minor version numbers with theirs, i.e. we would publish a `3.37.0` instead of a `3.0.0` when we make our official v3 release. While slightly constraining, this would be nice since it makes it obvious at a glance which `mapbox-gl` version you get with a given `react-map-gl` version.
* Decouple the two modules by going to a `peerDependency` - this would give users freedom to experiment with a new `mapbox-gl` release before we get around to updating. On the other hand, this may result in combinations that don't work. If we are able to bump frequently, I would not go this way.

**Comment by abmai** [comment]
I'm in favor of bumping minor versions every time we bump a `mapbox-gl` version. Sticking to their minor versioning **is** quite extreme and would eclipse our own minor versioning needs in my opinion.

> Some of their changes are breaking, which would technically mean react-map-gl should bump major version. Fortunately, many of their breaking changes are not be visible through our API (e.g. the mapboxgl.util removal above) so it may largely be a non-issue.

All of their changes happen under a minor version bump. It would be weird I think if we were to do major version bumps for their breaking changes when they do happen. I think we can just make sure we have robust testing in this case and list their breaking changes in our changelog as well.

**Comment by abmai** [comment]
Bumping to `0.37.0` will mean we have to remove code/tests that pull in any of the `mapboxgl.util` functions i.e. `transform`.
