### ISSUE TITLE
Consider removing mapboxgl-js as a depedency

### ISSUE THREAD

**Issue by vicapow** [uber/react-map-gl#31]
Even though the original intent of this library was to create a React friendly wrapper around MapboxGL-js, it's more or less just the bits of mapboxGL-js that handle the UI and viewport changes but in a React friendly (stateless) way as well as a few built in overlays and examples. The overlays themselves don't have a direct dependence on MapboxGL-js. They only require the necessary viewport state information. There could eventually be an independent `<MapboxGLOverlay>` instead.

**Comment by cusspvz** [comment]
+1
I'm currently trying to implement it on a project and I'm having issues with `mapbox-gl-js` module on bundling.

**Comment by vicapow** [comment]
Hey @cusspvz, the issue you're having might be unrelated. Could you provide more details?

**Comment by cusspvz** [comment]
After commenting here, I've found that issue #21 was actually what I was looking for, but then I've read some of the codebase and decided to keep my comment here.

**Comment by cusspvz** [comment]
In fact, I think this solution seems is a little bit nasty but, what if you require your `mapboxgl-js` dependencies from the files directly instead?

Since they aren't [ignoring](https://github.com/mapbox/mapbox-gl-js/blob/master/.npmignore) js folder.
`import LatLng from 'mapboxgl-js/js/geo/lng_lat.js'

Another solution would be `import { LatLng } from 'mapboxgl-js'`, but AFAIK, only [rollup](http://rollupjs.org/) is scrapping js for fetching what you really need from files ATM.

refs:
https://github.com/uber/react-map-gl/blob/3ec7c00c094ddd4b8fa44cf5503fb50f88b057f5/src/map.react.js#L28-L30
https://github.com/uber/react-map-gl/blob/56fd78cf65e06debcd504d4580351bcb14f3e9ee/src/map-interactions.react.js#L23-L24

**Comment by alex3165** [comment]
What about defining `mapbox-gl` as a peerdependency ? so that we could use the fix for the mapbox-gl files `mapbox-gl/js/render/shaders.js` and `webworkify/index.js` right ? cf https://github.com/uber/react-map-gl/issues/21

**Comment by abmai** [comment]
Closing this since there are multiple issues presented here and some are already resolved. feel free to create follow-ups if that's not the case.
