### ISSUE TITLE
width prop for interactive map is marked as required despite not being required

### ISSUE THREAD

**Issue by NLincoln** [uber/react-map-gl#362]
I just installed the lib. Omitting the width attr works fine, but it logs an annoying error to the console.

**Comment by ibgreen** [comment]
>Omitting the width attr works fine, but it logs an annoying error to the console.

@NLincoln - the `width` prop is used, e.g. when adding controls to the map etc.  

That said, in the upcoming react-map-gl 3.1 release we are planning to make it possible to omit explicit `width` and `height`, see e.g #341.

As input to that work maybe you could help us by answering this question: When you omit the `width` and `height` props, how do you size the map? (alternatively how would you prefer to control the size of the map?).

**Comment by lennerd** [comment]
> As input to that work maybe you could help us by answering this question: When you omit the `width` and `height` props, how do you size the map? (alternatively how would you prefer to control the size of the map?).

I would say it would be nice to just use the size of the container, like mapbox-gl itself is using it. So for example a `div` as a container has a default width `100%` of the parent element due to `display: block`. I usually just add a height to it and thats it. Media query support included.

I also wonder why controls are not added via mapbox-gl API. Why do we need an extra div element when mapbox already has a way to add controlls to different corners of the map.
