### ISSUE TITLE
Preventing map pan and zoom on page scroll

### ISSUE THREAD

**Issue by roma98** [uber/react-map-gl#393]
Hello,

I'm really happy about the new experimental MapControls component.
I've been wanting to reproduce this behavior for a while : [Preventing map pan and zoom on page scroll](https://developers.google.com/maps/documentation/javascript/interaction) 

right now, I'm disabling those events `['panstart', 'panmove', 'panend', 'wheel']`
- This is very convenient for mobile, since now a user can only interact with the map with two fingers, reproducing the desired behavior. Hower it's not possible anymore to move up and down the viewport when a `pan` event is triggered.
- On desktop, I would like to handle all the `pan` events, only when `Ctrl` key is pressed down...
Is it possible using the current `MapControls` component?

Thanks a lot.

**Comment by Pessimistress** [comment]
Can you show me how you are disabling those events?
In 3.1, the pan event is toggled by these two props: `dragPan` and `dragRotate` ([doc](https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map?section=properties)).

Because we are using hammerjs for gesture recognition, currently there's no easy way to unblock the default behavior as long as the pan event is registered. I agree it's a desirable feature especially for mobile.

A work around for you is to detect the type of the browser, and set both `dragPan` and `dragRotate` to false if it's mobile. The two-finger pan is actually handled by `pinch` event. You only need to handle `pan` and check for `ctrl` key if it's desktop.

**Comment by roma98** [comment]
Hey thanks for getting back to me! Here is my code

    class MapControls extends experimental.MapControls {

    constructor() {
        super();
        this.events = ['panstart', 'panmove', 'panend'];
    }

    handleEvent(event) {
        if (['panstart', 'panmove', 'panend'].indexOf(event.type) >= 0) {
            if (window.innerWidth < 600) {
                return false;
            }
            return super.handleEvent(event);
        }
        return super.handleEvent(event);
    }}

How do you check for `ctrl` key? I couln't catch the `keydown` event

**Comment by Pessimistress** [comment]
You can check with `event.srcEvent.ctrlKey`.
For your specific use case, I suggest you detect the browser type, and use something like
```
<MapGL ... dragPan={isDesktop} dragRotate={isDesktop} />
```
This will only capture drag events when it's rendered on desktop.

And for the desktop interaction, since you are not registering any new events, the easiest way is to just override the `_onPan` handler:
```
class MapControls extends experimental.MapControls {

  _onPan(event) {
    if (event.srcEvent.ctrlKey) {
      return this._onPanMove(event);
    }
    return false;
  }

}
```
The underscore methods are not documented at the moment. You'll need to see the [source](https://github.com/uber/react-map-gl/blob/3.1-release/src/utils/map-controls.js#L189) of pan event handling.

**Comment by roma98** [comment]
thank you so much!
