### ISSUE TITLE
Mouse events captured even for visibility: hidden

### ISSUE THREAD

**Issue by thunderkid** [uber/react-map-gl#514]
I'm finding that `react-map-gl` is still capturing mouse events even while it or a parent has `visibility: hidden`.
I have `react-map-gl` appearing on a tab. These tabs work by setting
```
visibility: hidden;
opacity: 0;
```
When I switch to a different tab, the components on this active tab aren't responding to mouse events - the hidden `react-map-gl` component is still capturing them instead.
I've tried this with and without `deck.gl`, and it's doing it in both cases.
However, when I create my own react wrapper for mapboxgl following [this](https://blog.mapbox.com/mapbox-gl-js-react-764da6cc074a) approach, the mouse events behave properly.

I'm using `react-map-gl 3.2.7`.

**Comment by Pessimistress** [comment]
This is because react-map-gl sets its own `visibility`, which overrides the parent's styling. You only made it invisible with `opacity: 0` which is not disabling events.

There are two ways we can fix this:
- Unmount the component when the tab is hidden.
- I could make a patch to allow the `style` prop on `InteractiveMap` to overwrite the internally generated `visibility` style.

Either way you must render differently when the tab shows/hides.
Thoughts?

**Comment by Pessimistress** [comment]
Actually, you can also target the map container using CSS:
`.tab.hidden .mapboxgl-map {visibility: hidden !important;}`

**Comment by edwinwebb** [comment]
You can also use `pointer-events: none` to pass through mouse events
