### ISSUE TITLE
Provide separate node and browser builds

### ISSUE THREAD

**Issue by TrySound** [uber/react-map-gl#557]
Mixed imports and requires does not make it possible to bundle react-map-gl based app with rollup.
https://github.com/uber/react-map-gl/blob/master/src/components/static-map.js#L32

I propose to provide separate bundles with necessary stuff and resolve them with `browser` package.json field.

Here's an example of how it will look like
https://github.com/styled-components/styled-components/blob/master/package.json#L10

If you agree with it I could start working on it.

**Comment by TrySound** [comment]
`process` stuff used by detectors is also will go and will prevent webpack from polyfilling it which should reduce user bundle size.
https://github.com/uber/react-map-gl/blob/master/src/utils/is-browser.js

**Comment by ibgreen** [comment]
> If you agree with it I could start working on it.

Yes, we'd welcome a PR, it would be great to support rollup. But let's just get all the complications clear. The biggest one may be that in contrast to many projects, we use pure ES6 source code (no ES7 etc) which allows us to run (test) our frameworks in node directly without any bundlers and transpilers.

So bundler based solutions that depend on the bundler making critical decisions for the node environment won't work without bigger changes. If possible I'd prefer not to change the node version to require a bundler since this is a setup we use across multiple repos and consistency helps us move around more easily.

So, as a "soft start", my proposal would be that you start by opening a simple PR on an `examples/exhibit-rollup` similar to the existing `exhibit-browserify and `exhibit-webpack` versions and we can all play around there and test solutions.

**Comment by ibgreen** [comment]
> process stuff used by detectors is also will go and will prevent webpack from polyfilling it which should reduce user bundle size.

Are you referring to the issue of getting the relatively small, otherwise unnecessary `process` polyfill bundled just because of this? Agree it would be desirable not to need it.

We have struggled to find an alternate solution which works reliably across bundlers and node. You are welcome to propose a new solution but let's keep the two things as separate discussions/PRs.

**Comment by TrySound** [comment]
I don't follow. How's node version is relative to my proposal? I propose only flat bundles. Any node version will be able to consume it.
> So bundler based solutions that depend on the bundler making critical decisions for the node environment won't work without bigger changes. If possible I'd prefer not to change the node version to require a bundler since this is a setup we use across multiple repos and consistency helps us move around more easily.

**Comment by TrySound** [comment]
One solution may eliminate both problems. `process` exists in the code because of browser detection.
> We have struggled to find an alternate solution which works reliably across bundlers and node. You are welcome to propose a new solution but let's keep the two things as separate discussions/PRs.

**Comment by ibgreen** [comment]
>  Any node version will be able to consume them.

My point is that our test suite runs the code without any bundling. If you add an unconditional `require` in there to something that only works on the browser, and rely on the bundler to not include it under Node, that wouldn't work. 

Not sure if it is an issue or not, but wanted to give you a heads up. You'd find out when you run the tests.

**Comment by ibgreen** [comment]
> process exists in the code because of browser detection. One solution may eliminate both problems. 

Perhaps you are right and it is only used in this place. I'd have to look through the code in this particular framework to see if it is used in multiple places. I can say that browser detection is typically used in several places across our frameworks to ensure things run both under node and browser.

We haven't really tackled running mapbox under node yet (requires installing additional dependencies), although it is of interest down the road both for better testing and offline rendering. 

But let's try solve this issue now and deal with those problems when we get there.

**Comment by TrySound** [comment]
I see you run test with both node and browser. It's trivial to mock some modules in jest to test in node, will investigate about mocking in your environment.
