### ISSUE TITLE
How to remove padding from Popup?

### ISSUE THREAD

**Issue by lappalj4** [uber/react-map-gl#716]
Is there a way to remove the padding (and/or background color) from the Popup component (without overriding the css style in my stylesheet)? Say I wanted to make the background of my popups red:

![screenshot 2019-02-05 at 18 26 38](https://user-images.githubusercontent.com/11797156/52287851-a3f17900-2973-11e9-87f1-6e1d2bab801c.png)

**Comment by xintongxia** [comment]
`react-map-gl` render a `Mapbox` popup component. 

If you want to use customized styles, you can override mapbox pop styles.

You can refer this [doc](https://docs.mapbox.com/help/tutorials/building-a-store-locator/) and search popup.

The following might be helpful.

```
.mapboxgl-popup-content {
  background: red;
}

.mapboxgl-popup-tip {
  background: red;
}

```

**Comment by disambiguator** [comment]
Are you all open to allowing dynamic styling of popups through inline styling? This current solution doesn't work for us because we decide popup color programmatically based on the element being hovered over.

I would love a solution similar to the way tipSize is able to be passed in, for example:
```
<Popup color:{'red'}>
  This is red
</Popup>
```
I'm happy to make a PR for this if there's interest.
