### ISSUE TITLE
1.0.0-beta release

### ISSUE THREAD

**Issue by ibgreen** [uber/react-map-gl#81]
See [README](https://github.com/uber/react-map-gl/blob/dev/README.md)
See [CHANGELOG](https://github.com/uber/react-map-gl/blob/dev/CHANGELOG.md)

**Comment by ibgreen** [comment]
Concerns about webpack issues were raised in https://github.com/uber/react-map-gl/pull/73
> Even despite using the transpiled files in dist/index.js, there are a couple other issues which arise from including some of react-map-gl's dependencies

@jwarning Just to clarify, it sounds like these problems were not introduced by the changes in the beta release (i.e. by the code in the dev branch: ES6 transpilation, code refactoring etc)? I.e. we should continue the discussion about webpack problems in issue 21.

**Comment by jwarning** [comment]
@ibgreen Yeah that is correct. They were present in the old branch as well.

**Comment by joewood** [comment]
Seems to regress #72 for react version peer dependency.

**Comment by ibgreen** [comment]
@joewood Just published `1.0.0-beta-9` which includes latest changes from master.

**Comment by tsemerad** [comment]
I'm using `1.0.0-beta-10`, and it's working great, except for style diffing. Is this a known issue of the beta? The changelog @ibgreen linked to can't be found.

**Comment by ibgreen** [comment]
@tsemerad 
> I'm using 1.0.0-beta-10, and it's working great, except for style diffing. Is this a known issue of the beta? 

The style diffing was lightly refactored in the beta. Can you give some details on what is not working? As a first step I'd like to understand if what you are seeing is a regression from 0.6.x, or perhaps you are hitting a bug that's in current master as well?

> The changelog @ibgreen linked to can't be found.

Updated the changelog link at the top of this thread, it should work now.

**Comment by tsemerad** [comment]
I first noticed the issue when adding new layers to the map - I have a button that toggles adding and removing a layer from the `layers` array in the mapbox style object. Toggling the layer will cause the whole map to flicker and reload.

I then decided to try just changing the map's background color instead of adding a layer, and that too causes the reload.

**Comment by tsemerad** [comment]
Here's the code I used to test changing the background color (with `state.mapboxStyle` being `Immutable.fromJS(someMapboxJsonObject)`):

```javascript
return state.updateIn(['mapboxStyle', 'layers'], (layers) => {
  const index = layers.findIndex((item) => item.get('id', 'background'))
    if (index > -1) {
      return layers.update(index, (item) => item.set('paint', Immutable.Map({'background-color': 'red'})))
    }
    return state
  })
}
```

**Comment by tsemerad** [comment]
I found the problem! It turns out, having a `metadata` attribute in the style JSON is causing the whole style to reload. I had this:

```json
    "metadata": {
        "mapbox:autocomposite": true,
        "mapbox:type": "default"
    },
```

Removing the entire `metadata` attribute solved the issue. I don't need the `metadata` anyway - it's just a remnant from when I exported the style from Mapbox. I reproduced the issue in the `style-diffing.react.js` example by adding `metadata` to it. Would you like me to file an issue for it?

**Comment by ibgreen** [comment]
Merged to master and published on npm
