### ISSUE TITLE
right to left languages has not been supported by react-map-gl

### ISSUE THREAD

**Issue by mosy1378** [uber/react-map-gl#834]
i am using react-map-gl library in my react app and it does not show persian words in the currect way in map . is there any way to solve this problem??

**Comment by Pessimistress** [comment]
This has nothing to do with react-map-gl, you need to call the mapbox-gl API:
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/

**Comment by NameFILIP** [comment]
@Pessimistress similar to setting the `accessToken` in the example you've shared:
```
mapboxgl.accessToken = '<your access token here>';
```
the `setRTLTextPlugin` also needs to be called on `mapboxgl`:
```
mapboxgl.setRTLTextPlugin(
  'https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.3/mapbox-gl-rtl-text.js',
  null,
  true // Lazy load the plugin
);
```
The problem is that it's a little bit tricky to get access to the `mapboxgl` object. Would it make sense to expose either the `mapboxgl` or only the `setRTLTextPlugin(..)`  out of the `react-map-gl` map instance?
